-- Fresh migration history for product-service, seeded from the SHAPE
-- oms-main's "products" table had reached as of the Phase 4 extraction —
-- NOT a copy of oms-main's V1/V8/V10/V17 migration chain. That history
-- included a "stock" column that was added then dropped, and a status
-- column added later via ALTER TABLE — none of that intermediate history is
-- meaningful here; this service starts from the end state directly.
--
-- version (optimistic locking, see common.entity.BaseEntity) and status
-- (soft-delete, see product.entity.ProductStatus — Phase 1 of the
-- microservices-prep plan) are both included from the start, unlike
-- oms-main where they were retrofitted via later migrations.

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price       NUMERIC(7,2) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'DISCONTINUED'))
);

CREATE INDEX idx_products_name ON products (name);
CREATE INDEX idx_products_status ON products (status);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_products_name_trgm ON products USING gin (name gin_trgm_ops);
